### ISSUE TITLE
"Can the final prediction results be visualized with CloudCompare?"

### ISSUE THREAD

**Issue by jia1047** [mellody11/RandLA-Net-Pytorch-New#11]
"Can the final prediction results be visualized with CloudCompare?"

**Comment by mellody11** [comment]
Hi, jia1047. The final prediction results only contain the prediction and label, so it can not directly be visualized with CloudCompare. https://github.com/mellody11/RandLA-Net-Pytorch-New/blob/b0f7bbcaf61c183d5c8d5a3ab1a675d32fa60a09/test_S3DIS.py#L218

You can load the point cloud scene and get the _xyz_ and _rgb_ attribute and save as the _.ply_ file together with the prediction and label.

**Comment by jia1047** [comment]
May I ask if the code can also be used normally with torch 2.3.0? Thank you.
