### ISSUE TITLE
In the `test_SemanticKITTI.py` file, why does `new_min` in the log statement `log_string('Epoch {:3d}, end. Min possibility = {:.1f}'.format(epoch_ind, new_min))` remain at 0.0 after several rounds of execution?

### ISSUE THREAD

**Issue by sobigrain** [mellody11/RandLA-Net-Pytorch-New#14]
In the `test_SemanticKITTI.py` file, why does `new_min` in the log statement `log_string('Epoch {:3d}, end. Min possibility = {:.1f}'.format(epoch_ind, new_min))` remain at 0.0 after several rounds of execution?

**Comment by mellody11** [comment]
several 是多少？我看我之前的log，从Epoch 7 开始这个概率就会变

**Comment by sobigrain** [comment]
哇，谢谢佬抽空给我回复。但是你口中是不是打印了几次? 如果是的话那么我的Epoch没到7我就停下来debug了！谢谢你的代码了。佬发了论文请在githup上给个链接。我要是能引用我就引用。我也是点云语义分割方向的。你的代码能力好强！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mellody11/RandLA-Net-Pytorch-New"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mellody11/RandLA-Net-Pytorch-New] In the `test_SemanticKITTI.py` file, why does `new_min` in the log statement `log_string('Epoch {:3d}, end. Min possibility = {:.1f}'.format(epoch_ind, new_min))` remain at 0.0 after several rounds of execution? (Issue #14)





 
several 是多少？我看我之前的log，从Epoch 7 开始这个概率就会变

**Comment by sobigrain** [comment]
嗯，那就是我没有等到Epoch 到 7，我看到好久都不变我就停下来debug了！谢谢你了！

**Comment by mellody11** [comment]
是要跑得比较久的，你可以多跑一会看看，再有问题可以再继续问。

我不是啥大佬哇，这个代码其实很多是来自另外一个仓库的，主要思路也是他的，我只是将它扩展到了semanticKITTI数据集而已，我也还在学习中，一起加油~
