### ISSUE TITLE
random seed

### ISSUE THREAD

**Issue by jia1047** [mellody11/RandLA-Net-Pytorch-New#15]
May I ask if you have a fixed random seed? I saw that in the main_S3DIS file, you wrote 'def train (start_ epoch)' to np. random. seed(), but did not specify a specific value. As a result, the results of each run will change and be unstable

**Comment by jia1047** [comment]
May I ask how much is usually set, 42?

**Comment by mellody11** [comment]
In my opinion, setting a random number seed has no other meaning in practical applications besides achieving repeatability. You can set it to any number
