### ISSUE TITLE
SensatUrban 

### ISSUE THREAD

**Issue by jia1047** [mellody11/RandLA-Net-Pytorch-New#17]
Do you have any data preprocessing files, training files, and testing files for the SensatUrban dataset in Pytorch version? thank you

**Comment by mellody11** [comment]
I haven't tried using SensatUrban before. You can search for other works if they use this dataset.

**Comment by wantasci** [comment]
> 请问您有适用于 PyTorch 版本的 SensatUrban 数据集的数据预处理文件、训练文件和测试文件吗？谢谢！

您好，我想请问一下您有适用于 PyTorch 版本的 SensatUrban 城市点云数据集的数据预处理文件、训练文件和测试文件吗？谢谢！

**Comment by liuxuexun** [comment]
> > 请问您有适用于 PyTorch 版本的 SensatUrban 数据集的数据预处理文件、训练文件和测试文件吗？谢谢！
> 
> 您好，我想请问一下您有适用于 PyTorch 版本的 SensatUrban 城市点云数据集的数据预处理文件、训练文件和测试文件吗？谢谢！

抱歉，我还没有在这个数据集上尝试过，通常数据预处理文件不涉及具体的训练框架，你可以看看一些开源的仓库有没有，或者求助一下RandLA-Net的作者，我记得这个数据集是他们做的。

**Comment by wantasci** [comment]
> > > 请问您有适用于PyTorch版本的SensatUrban数据集的数据文件、训练文件和测试文件吗？谢谢！
> > 
> > 
> > 您好，我想问一下您有适用于PyTorch版本的SensatUrban城市点云数据集的数据文件、训练文件和测试文件吗？谢谢！
> 
> 抱歉，我还没有在这个数据集上尝试过，通常数据修复文件不涉及具体的训练框架，你可以看看一些开源的仓库有没有，或者求助一下RandLA-Net的作者，我记得这个数据集是他们做的。

好的，非常感谢

**Comment by wantasci** [comment]
> > > 请问您有适用于 PyTorch 版本的 SensatUrban 数据集的数据预处理文件、训练文件和测试文件吗？谢谢！
> > 
> > 
> > 您好，我想请问一下您有适用于 PyTorch 版本的 SensatUrban 城市点云数据集的数据预处理文件、训练文件和测试文件吗？谢谢！
> 
> 抱歉，我还没有在这个数据集上尝试过，通常数据预处理文件不涉及具体的训练框架，你可以看看一些开源的仓库有没有，或者求助一下RandLA-Net的作者，我记得这个数据集是他们做的。

<img width="1136" height="623" alt="Image" src="https://github.com/user-attachments/assets/cedfefca-7e03-49e3-ab6d-c1094f554a6a" />这个是我按照您的代码进行模仿编写的关于SensatUrban数据集的代码，但是我总感觉有问题，能否请您帮我看下
