### ISSUE TITLE
Test results

### ISSUE THREAD

**Issue by LREM-C** [mellody11/RandLA-Net-Pytorch-New#2]
Is the final test value the result of inference back to the original point cloud, or is it the result of evaluate in the training main file?

**Comment by mellody11** [comment]
Hi, the result is back to the original point cloud.

**Comment by LREM-C** [comment]
How long does a round take?

**Comment by mellody11** [comment]
It depends on your device.

I train 100 epoch about 12 hours with Tesla V100.

A epoch takes within 10 min.
