### ISSUE TITLE
牛啊

### ISSUE THREAD

**Issue by AlberTgarY** [mellody11/RandLA-Net-Pytorch-New#4]
牛啊兄弟，去年研究tensorflow v1垃圾代码研究头都快爆炸了，pytorch清楚多了  😀

**Comment by mellody11** [comment]
谢谢您对本工作的欣赏，其实本工作很大一部分是基于其他开源代码的，您可以进一步了解[这些](https://github.com/qiqihaer/RandLA-Net-pytorch)优秀工作。
