### ISSUE TITLE
gcc: error: knn.cxx: 没有那个文件或目录  error: command '/usr/bin/gcc' failed with exit code 1 running build_ext

### ISSUE THREAD

**Issue by jc991206** [mellody11/RandLA-Net-Pytorch-New#6]
/home/zjd/anaconda3/envs/randla-torch/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/zjd/anaconda3/envs/randla-torch/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
TEST FAILED: ./lib/python/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    ./lib/python/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
gcc: error: knn.cxx: 没有那个文件或目录
error: command '/usr/bin/gcc' failed with exit code 1
running build_ext

**Comment by jc991206** [comment]
请问一下，这个问题该怎么解决呢

**Comment by jc991206** [comment]
parser.add_argument('--checkpoint_path', default='output/checkpoint_Area_1.tar', help='Model checkpoint path [default: None]')请问test里面的这个check point指的是什么？我看您的代码里面没有这个文件out/checkpoint_Area_1.tar,这个地方该如何修改呢


1697909415
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mellody11/RandLA-Net-Pytorch-New"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月7日(星期四) 晚上11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mellody11/RandLA-Net-Pytorch-New] gcc: error: knn.cxx: 没有那个文件或目录  error: command '/usr/bin/gcc' failed with exit code 1 running build_ext (Issue #6)





 
您好，后面在邮件联系吧。

**Comment by Vonct** [comment]
> 请问一下，这个问题该怎么解决呢

请问你解决了吗？一直编译不了，说找不到knn.cxx

**Comment by mellody11** [comment]
> > 请问一下，这个问题该怎么解决呢
> 
> 请问你解决了吗？一直编译不了，说找不到knn.cxx

应该是Cython版本不对，你装readme的那个版本试试。

**Comment by Vonct** [comment]
> > > 请问一下，这个问题该怎么解决呢
> > 
> > 
> > 请问你解决了吗？一直编译不了，说找不到knn.cxx
> 
> 应该是Cython版本不对，你装readme的那个版本试试。

确实，我现在编译成功了，在lib下生成了nearest_neighbors.cpython-38-x86_64-linux-gnu.so，但是我在import nearest_neighbors时，又报了一个错
ModuleNotFoundError: No module named 'utils.nearest_neighbors.lib.python.nearest_neighbors'
请问你知道怎么解决吗？

**Comment by mellody11** [comment]
> > > > 请问一下，这个问题该怎么解决呢
> > > 
> > > 
> > > 请问你解决了吗？一直编译不了，说找不到knn.cxx
> > 
> > 
> > 应该是Cython版本不对，你装readme的那个版本试试。
> 
> 确实，我现在编译成功了，在lib下生成了nearest_neighbors.cpython-38-x86_64-linux-gnu.so，但是我在import nearest_neighbors时，又报了一个错 ModuleNotFoundError: No module named 'utils.nearest_neighbors.lib.python.nearest_neighbors' 请问你知道怎么解决吗？

你好，我这边没有复现到你的这个问题，你可以再看看readme，确认是否按照readme进行操作。如果还是不行，则请安装python3.7，跳过sh编译步骤

**Comment by GODBENGAY** [comment]
> > > 请问一下，这个问题该怎么解决呢
> > 
> > 
> > 请问你解决了吗？一直编译不了，说找不到knn.cxx
> 
> 应该是Cython版本不对，你装readme的那个版本试试。

是的 pip install cython==0.29.15就好
