### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by anonymouslosty** [mellody11/RandLA-Net-Pytorch-New#8]
您好，semantic_kitti_dataset.py中 第91行，pc_path = self.data_list[cloud_ind]。
这一行代码有BUG
参考您所引用的代码，这一行是否应该改为pc_path = self.path_list[cloud_ind] ？

**Comment by mellody11** [comment]
您好，非常感谢您提出的这个问题，这确实是我工作的疏忽，原来我上传的一直是一个错误的仓库。

我会及时更新我的代码，新的代码与旧的代码会有所不同。

最后在此对所有对本工作感兴趣的社区朋友说声抱歉。

**Comment by sobigrain** [comment]
你好，您的代码实在是太美了。而且还是比较新的pytorch的版本。但是不幸的是我在运行test_SemanticKITTI.py去测试08区域的时候出现了报错。目前看来是if np.min(dataset.min_possibility) > 0.5这一行代码始终满足不了。我也不知道为什么，然后我就看看到底运行了多少遍于是我就在第194行的continue上面打印了你的epoch_ind += 1。发现就运行了一次就直接”被系统杀死“导致程序停止了。
![Uploading 3123418802e498296cb8ed7623e1b9c.jpg…]()
