### ISSUE TITLE
Error on test_semantickitti

### ISSUE THREAD

**Issue by Vonct** [mellody11/RandLA-Net-Pytorch-New#9]
When I try to test on kitti after training, there is an error:

Traceback (most recent call last):
  File "test_SemanticKITTI.py", line 305, in <module>
    
  File "test_SemanticKITTI.py", line 150, in test
    cfg.num_classes])
RuntimeError: shape '[20, 45056, 19]' is invalid for input of size 9416704

line 150 is: stacked_probs = torch.reshape(stacked_probs, [cfg.val_batch_size, cfg.num_points,  cfg.num_classes]) 
how can i fix this?

我看您注释里也有写到说是这一行可能有问题，不知道要怎么修改呢？

**Comment by mellody11** [comment]
我这里运行了一遍没有报这个错误，你可以看看142行的stacked_probs的维度是不是(20, 45056, 19)

**Comment by Vonct** [comment]
我print了一下，在142行是torch.Size([901120, 19])，这时候在执行148行是不会报错的。但是可能是在RuntimeError: shape '[20, 45056, 19]' is invalid for input of size 856064, 设置了drop_last=True就好了。
不过我在此测试的时候，运行了很久都没结束，看了下代码退出循环是和一个if条件有关，请问一下推出循环的条件详细一点来说是什么意思呢？

**Comment by mellody11** [comment]
推理阶段是一个voting的过程，以提高最终的成绩，期间会进行多个epoch的推理，当点的选择概率到一定的时候会跳出循环。

**Comment by Vonct** [comment]
我没找到min_possibility是怎么更新的，貌似都没出现过dataset.min_possibility的修改？然后我跑了两个epoch，都是显示Min_possibility=0
另外，不知道是否可以分享下权重文件呢？我点进去readme中的连接发现需要没有访问权限。

**Comment by mellody11** [comment]
1. min_possibility是在dataset里面更新的，每拿一次数据都会更新一次。
2. 权重文件权限已开，感谢提醒。
3. 代码在别的地方有bug，将会在今天修复，谢谢您的提出。

**Comment by mellody11** [comment]
bug已修复，您可以再拉取一下仓库，如果还有问题欢迎随时提出。

The bug has been fixed. You can pull the repo. again and feel free to raise any further questions.

**Comment by Vonct** [comment]
好的，我现在再试一下

**Comment by mellody11** [comment]
谢谢你的反馈，已经修改为08了。
